server:
  port: 8080
  servlet:
    encoding:
      charset: utf8
      enabled: true
      force: true
spring:
  application:
    name: vrmanager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.135.175:3306/vrmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: dev
    password: dev@1298
  devtools:
    restart:
      enabled: true